/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG */

#ifndef _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
#define _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
#ifdef __cplusplus
extern "C" {
#endif
#undef de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_POINT_IN_TIME_C
#define de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_POINT_IN_TIME_C 80L
#undef de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_INTERVAL_IN_TIME_C
#define de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_INTERVAL_IN_TIME_C 73L
#undef de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_POINT_IN_TIME_UCS
#define de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_POINT_IN_TIME_UCS 112L
#undef de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_INTERVAL_IN_TIME_UCS
#define de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_EVENT_INTERVAL_IN_TIME_UCS 105L
/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    attach
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_attach
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    gettime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_gettime
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    sgettime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_sgettime
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    write
 * Signature: (IIIJJ)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_write__IIIJJ
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    write
 * Signature: (IIIJJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_write__IIIJJLjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong, jstring);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    write
 * Signature: (IIIJJLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_write__IIIJJLjava_lang_String_2I
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong, jstring, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    write
 * Signature: (IIIJJLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_write__IIIJJLjava_lang_String_2II
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong, jstring, jint, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    write
 * Signature: (IIIJJ[B)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_write__IIIJJ_3B
  (JNIEnv *, jobject, jint, jint, jint, jlong, jlong, jbyteArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getStatisticsMaxIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getStatisticsMaxIndex
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getStatistics
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getStatistics
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    sleepNanos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_sleepNanos
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setEnvPrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setEnvPrefix
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEnvPrefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEnvPrefix
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEnv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEnvShmid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEnvShmid
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEnvIdSuffix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEnvIdSuffix
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getMinorVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getMinorVersion
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getPatchVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getPatchVersion
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEventLocksMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEventLocksMax
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setEventLocksMax
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setEventLocksMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getEvent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setEventOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setEventOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setEventOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setEventOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getLogging
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getLogging
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setLoggingProcessOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setLoggingProcessOn
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setLoggingProcessOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setLoggingProcessOff
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setLoggingProcessOffFinal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setLoggingProcessOffFinal
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getShmid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getShmid
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getArea
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getArea
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAreaIchHabeFertig
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAreaIchHabeFertig
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setAreaIchHabeFertig
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setAreaIchHabeFertig
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAreaCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAreaCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAreaVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAreaVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getBufferMaxSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getBufferMaxSize
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getFListBufferSlaveCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getFListBufferSlaveCount
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setFListBufferSlaveCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setFListBufferSlaveCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getClockId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getClockId
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setClockId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setClockId
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setFListBufferSlaveRunOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setFListBufferSlaveRunOff
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setWaitForSlavesOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setWaitForSlavesOn
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setWaitForSlavesOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setWaitForSlavesOff
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getWaitForSlaves
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getWaitForSlaves
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getFListBufferSlaveWait
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getFListBufferSlaveWait
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setFListBufferSlaveWait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setFListBufferSlaveWait
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAcquireCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAcquireCount
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getPreallocBufferCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getPreallocBufferCount
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setPreallocBufferCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setPreallocBufferCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getInittime
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getInittime
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getInittimeTscBefore
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getInittimeTscBefore
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getInittimeTscAfter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getInittimeTscAfter
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getBufferId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getBufferId
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_stop
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_flush
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setStrategy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setStrategy
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getStrategy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getStrategy
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setStrategyProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setStrategyProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getStrategyProcess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getStrategyProcess
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    createSlave
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_createSlave
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    decrementSlaveCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_decrementSlaveCount
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence1
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence1
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence2
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence2
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence3
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence3
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence3
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence4
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence4
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence4
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence4
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence5
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence5
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence5
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence5
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence6
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence6
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence6
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence7
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence7
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence7
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence7
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence8
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence8
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence8
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence9
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence9
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence9
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence9
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence10
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence10
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence10
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence10
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence11
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence11
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence11
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence11
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence12
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence12
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence12
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence12
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setThreadFence13
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setThreadFence13
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadFence13
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadFence13
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getRealtime
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getRealtime
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadLocalsAdress
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadLocalsAdress
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getTid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getTid
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    turnLoggingOff
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_turnLoggingOff
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setInitBuffersInAdvanceOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setInitBuffersInAdvanceOn
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setInitBuffersInAdvanceOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setInitBuffersInAdvanceOff
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getInitBuffersInAdvance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getInitBuffersInAdvance
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getNextSlaveLocal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getNextSlaveLocal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getThreadLocalTid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getThreadLocalTid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    removeSlaveViaLocal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_removeSlaveViaLocal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    reuseThreadBuffers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_reuseThreadBuffers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setAutoflushProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setAutoflushProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAutoflushProcess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAutoflushProcess
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setAutoflush
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setAutoflush
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getAutoflush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getAutoflush
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    turnSlaveOff
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_turnSlaveOff
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getSlaveTid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getSlaveTid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    setChecksum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_setChecksum
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getChecksum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getChecksum
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    verify
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_verify
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    getClicktime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_getClicktime
  (JNIEnv *, jobject);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    read
 * Signature: (JI[B[J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_read
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jlongArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    readFetch
 * Signature: (J[B[J)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_readFetch
  (JNIEnv *, jobject, jlong, jbyteArray, jlongArray);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    create
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_create
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    delete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    cleanupLocks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_cleanupLocks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    initShmLog
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_initShmLog
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    peek
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_peek
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG
 * Method:    poke
 * Signature: (JIB)I
 */
JNIEXPORT jint JNICALL Java_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_poke
  (JNIEnv *, jobject, jlong, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_strategy */

#ifndef _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_strategy
#define _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_strategy
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_error */

#ifndef _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_error
#define _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_error
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_counter */

#ifndef _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_counter
#define _Included_de_atrsoft_successorofoak_utilities_logging_atrshmlog_ATRSHMLOG_atrshmlog_counter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
