/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjnipackage_HelloJNI */

#ifndef _Included_myjnipackage_HelloJNI
#define _Included_myjnipackage_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjnipackage_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjnipackage_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
