#!/usr/bin/perl
#!/usr/local/bin/perl
#!/usr/pkg/bin/perl
#
# $Id:$
#
# we deliver a human text for an error code.
#
%error_map = (
    0 => [ 'atrshmlog_error_ok ' , 'Operation was successful, no error.' ] ,
    
    -1 => [ 'atrshmlog_error_error ' , 'Generic error 1 happend.' ] ,
    
    -2 => [ 'atrshmlog_error_error2 ' , 'Generic error 2 happend. ' ] ,
    
    -3 => [ 'atrshmlog_error_error3 ' , 'Generic error 3 happend. ' ] ,
    
    -4 => [ 'atrshmlog_error_error4 ' , 'Generic error 4 happend. ' ] ,
    
    -5 => [ 'atrshmlog_error_error5 ' , 'Generic error 5 happend. ' ] ,
    
    -11 => [ 'atrshmlog_error_connect_1 ' , 'Buffer list is NULL in atrshmlog_il_connect_buffers_list. ' ] ,
    
    -12 => [ 'atrshmlog_error_connect_2 ' , 'Buffer count is negative in atrshmlog_il_connect_buffers_list. ' ] ,
    
    -21 => [ 'atrshmlog_error_init_thread_local_1 ' , 'The init was not successful in atrshmlog_init_thread_local. ' ] ,
    
    -31 => [ 'atrshmlog_error_mem_to_shm_1 ' , 'The shared memory is not connected in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    -32 => [ 'atrshmlog_error_mem_to_shm_2 ' , 'The transfer buffer is NULL in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    31 => [ 'atrshmlog_error_mem_to_shm_3 ' , 'The size is 0, no operation in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    -33 => [ 'atrshmlog_error_mem_to_shm_4 ' , 'The maximum size is exceeded in atrshmlog_transfer_mem_to_shm for the buffer itself. ' ] ,
    
    -34 => [ 'atrshmlog_error_mem_to_shm_5 ' , 'The logging was off for the thread in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    -35 => [ 'atrshmlog_error_mem_to_shm_6 ' , 'The safeguard was corrupt in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    32 => [ 'atrshmlog_error_mem_to_shm_7 ' , 'The logging was off for the system in area for atrshmlog_transfer_mem_to_shm. ' ] ,

    33 => [ 'atrshmlog_error_mem_to_shm_8 ' , 'The logging was final off in atrshmlog_transfer_mem_to_shm. ' ] ,
    
    41 => [ 'atrshmlog_error_attach_1 ' , 'The attach was already done in atrshmlog_attach. ' ] ,
    
    -41 => [ 'atrshmlog_error_attach_2 ' , 'Could not find a valid environment or file approch in atrshmlog_attach. ' ] ,
    
    -42 => [ 'atrshmlog_error_attach_3 ' , 'The cleanup could not sucessful made atexit in atrshmlog_attach. ' ] ,
    
    -43 => [ 'atrshmlog_error_attach_4 ' , 'The flagfile seems to be corrupt in atrshmlog_attach. ' ] ,
    
    -44 => [ 'atrshmlog_error_attach_5 ' , 'No flagfile option for this level in atrshmlog_attach. ' ] ,
    
    -45 => [ 'atrshmlog_error_attach_6 ' , 'The cleanup could not sucessful made atexit in atrshmlog_attach.  ' ] ,
    
    -51 => [ 'atrshmlog_error_init_in_write_1 ' , 'Buffer allocation failure in atrshmlog_init_in_write. ' ] ,
    
    -61 => [ 'atrshmlog_error_write0_1 ' , 'Eventnumber negative in atrshmlog_write0. ' ] ,
    
    -62 => [ 'atrshmlog_error_write0_2 ' , 'Eventnumber too big in atrshmlog_write0. ' ] ,
    
    -63 => [ 'atrshmlog_error_write0_3 ' , 'Logging off for the thread in atrshmlog_write0. ' ] ,
    
    61 => [ 'atrshmlog_error_write0_4 ' , 'Buffer full discard in atrshmlog_write0. ' ] ,
    
    62 => [ 'atrshmlog_error_write0_5 ' , 'Logging off final in atrshmlog_write0. ' ] ,
    
    63 => [ 'atrshmlog_error_write0_6 ' , 'Logging off in area in atrshmlog_write0. ' ] ,
    
    -64 => [ 'atrshmlog_error_write0_7 ' , 'Safeguard corrupt in atrshmlog_write0. ' ] ,
    
    -65 => [ 'atrshmlog_error_write0_8 ' , 'Area safeguard corrupt in atrshmlog_write0. ' ] ,
    
    64 => [ 'atrshmlog_error_write0_9 ' , 'Logging off in area  atrshmlog_write0. ' ] ,
    
    -71 => [ 'atrshmlog_error_write1_1 ' , 'Size payload is negative in atrshmlog_write1. ' ] ,
    
    -72 => [ 'atrshmlog_error_write1_2 ' , 'Eventnumber negative in atrshmlog_write1. ' ] ,
    
    -73 => [ 'atrshmlog_error_write1_3 ' , 'Eventnumber too big in atrshmlog_write1. ' ] ,
    
    -74 => [ 'atrshmlog_error_write1_4 ' , 'Payload too big for logging in atrshmlog_write1. ' ] ,
    
    -75 => [ 'atrshmlog_error_write1_5 ' , 'Logging off for the thread in atrshmlog_write1. ' ] ,
    
    71 => [ 'atrshmlog_error_write1_6 ' , 'Buffer full discard in  atrshmlog_write1. ' ] ,
    
    72 => [ 'atrshmlog_error_write1_7 ' , 'Logging off final in atrshmlog_write1. ' ] ,
    
    73 => [ 'atrshmlog_error_write1_8 ' , 'Logging off in area in atrshmlog_write1. ' ] ,
    
    -76 => [ 'atrshmlog_error_write1_9 ' , 'Payload too big for logging in atrshmlog_write1. ' ] ,
    
    -77 => [ 'atrshmlog_error_write1_10 ' , 'Safeguard corrupt in atrshmlog_write1. ' ] ,
    
    -78 => [ 'atrshmlog_error_write1_11 ' , 'Area safeguard corrupt in atrshmlog_write1. ' ] ,
    
    74 => [ 'atrshmlog_error_write1_12 ' , 'Logging off in area in atrshmlog_write1. ' ] ,
    
    -81 => [ 'atrshmlog_error_write2_1 ' , 'Size payload is negative in atrshmlog_write2. ' ] ,
    
    -82 => [ 'atrshmlog_error_write2_2 ' , 'Eventnumber negative in atrshmlog_write2. ' ] ,
    
    -83 => [ 'atrshmlog_error_write2_3 ' , 'Eventnumber too big in atrshmlog_write2. ' ] ,
    
    -84 => [ 'atrshmlog_error_write2_4 ' , 'Payload too big for logging in atrshmlog_write2. ' ] ,
    
    -85 => [ 'atrshmlog_error_write2_5 ' , 'Logging off for the thread in atrshmlog_write2. ' ] ,
    
    81 => [ 'atrshmlog_error_write2_6 ' , 'Buffer full discard in atrshmlog_write2. ' ] ,
    
    82 => [ 'atrshmlog_error_write2_7 ' , 'Logging off final in  atrshmlog_write2. ' ] ,
    
    83 => [ 'atrshmlog_error_write2_8 ' , 'Logging off in area in  atrshmlog_write2. ' ] ,
    
    -86 => [ 'atrshmlog_error_write2_9 ' , 'Payload too big for logging in atrshmlog_write2. ' ] ,
    
    -87 => [ 'atrshmlog_error_write2_10 ' , 'Safeguard corrupt in atrshmlog_write2. ' ] ,
    
    -88 => [ 'atrshmlog_error_write2_11 ' , 'Area safeguard corrupt in atrshmlog_write2. ' ] ,
    
    84 => [ 'atrshmlog_error_write2_12 ' , 'Logging off in area in  atrshmlog_write2. ' ] ,
    
    -91 => [ 'atrshmlog_error_area_version_1 ' , 'Area not connected in atrshmlog_get_area_version. ' ] ,
    
    -101 => [ 'atrshmlog_error_area_count_1 ' , 'Area not connected in atrshmlog_get_area_count. ' ] ,
    
    -111 => [ 'atrshmlog_error_area_ich_habe_fertig_1 ' , 'Area not connected in atrshmlog_set_area_ich_habe_fertig. ' ] ,
    
    -121 => [ 'atrshmlog_error_get_event_1 ' , 'Index out of range in atrshmlog_get_event. ' ] ,
    
    131 => [ 'atrshmlog_error_get_logging_1 ' , 'Area not connected in atrshmlog_get_logging. ' ] ,
    
    132 => [ 'atrshmlog_error_get_logging_2 ' , 'Area logging flag off in atrshmlog_get_logging. ' ] ,
    
    133 => [ 'atrshmlog_error_get_logging_3 ' , 'Logging final off in atrshmlog_get_logging. ' ] ,
    
    134 => [ 'atrshmlog_error_get_logging_4 ' , 'Process logging off in atrshmlog_get_logging. ' ] ,
    
    -141 => [ 'atrshmlog_error_create_1 ' , 'Ipc key out of range in atrshmlog_create. ' ] ,
    
    -142 => [ 'atrshmlog_error_create_2 ' , 'Buffer count to low in  atrshmlog_create. ' ] ,
    
    -143 => [ 'atrshmlog_error_create_3 ' , 'Buffer count to high in  atrshmlog_create. ' ] ,
    
    -144 => [ 'atrshmlog_error_create_4 ' , 'Connect failed in low level call in atrshmlog_create. ' ] ,
    
    -151 => [ 'atrshmlog_error_init_shm_1 ' , 'Area is NULL in atrshmlog_init_shm_log. ' ] ,
    
    -152 => [ 'atrshmlog_error_init_shm_2 ' , 'Shared memory id diffrent for process and area in atrshmlog_init_shm_log. ' ] ,
    
    -153 => [ 'atrshmlog_error_init_shm_3 ' , 'Low level init failed in atrshmlog_init_shm_log. ' ] ,
    
    -161 => [ 'atrshmlog_error_read_1 ' , 'Area is NULL in atrshmlog_read. ' ] ,
    
    -162 => [ 'atrshmlog_error_read_2 ' , 'Buffer index negative in atrshmlog_read. ' ] ,
    
    -163 => [ 'atrshmlog_error_read_3 ' , 'Buffer index too big in atrshmlog_read. ' ] ,
    
    -164 => [ 'atrshmlog_error_read_4 ' , 'Area safeguard corrupt in atrshmlog_read. ' ] ,
    
    -165 => [ 'atrshmlog_error_read_5 ' , 'Buffer size in shared memory too big in atrshmlog_read. ' ] ,
    
    -171 => [ 'atrshmlog_error_read_fetch_1 ' , 'Area is NULL in atrshmlog_read_fetch. ' ] ,
    
    -172 => [ 'atrshmlog_error_read_fetch_2 ' , 'Area safeguard corrupt in atrshmlog_read_fetch. ' ] ,
    
    171 => [ 'atrshmlog_error_read_fetch_3 ' , 'No buffer to be processed in atrshmlog_read_fetch. ' ] ,
    
    -173 => [ 'atrshmlog_error_read_fetch_4 ' , 'Buffer size in shared memory too big in atrshmlog_read_fetch. ' ] ,
    
    172 => [ 'atrshmlog_error_read_fetch_5 ' , 'Buffer has size 0 in shared memory too big in atrshmlog_read_fetch. ' ] ,
    
    -181 => [ 'atrshmlog_error_verify_1 ' , 'Area not attached in atrshmlog_verify. ' ] ,
    
    -182 => [ 'atrshmlog_error_verify_2 ' , 'Shared memory id differs to process shared memory id in atrshmlog_verify. ' ] ,
    
    -183 => [ 'atrshmlog_error_verify_3 ' , 'Area safeguard corrupted in atrshmlog_verify. ' ] ,
    
    -184 => [ 'atrshmlog_error_verify_4 ' , 'Version mismatch for area and module code in atrshmlog_verify. ' ] ,
    
    -185 => [ 'atrshmlog_error_verify_5 ' , 'Area buffer state corrupt in atrshmlog_verify. ' ] ,
    
    -186 => [ 'atrshmlog_error_verify_6 ' , 'Buffer safeguard corrupted in atrshmlog_verify. ' ] ,
    
    -190 => [ 'atrshmlog_error_buffer_slave_1 ' , 'Pthread specific buffer not available. ' ] ,

    -191 => [ 'atrshmlog_error_get_strategy_1 ' , 'Pthread specific buffer not available. ' ] ,

    -166 => [ 'atrshmlog_error_read_6 ' , 'Pthread specific buffer not available. ' ] ,

    -174 => [ 'atrshmlog_error_read_fetch_6 ' , 'Pthread specific buffer not available. ' ] ,

    -192 => [ 'atrshmlog_error_set_strategy_1 ' , 'Pthread specific buffer not available. ' ] ,

    -66 => [ 'atrshmlog_error_write0_10 ' , 'Pthread specific buffer not available. ' ] ,

    -79 => [ 'atrshmlog_error_write1_13 ' , 'Pthread specific buffer not available. ' ] ,

    -89 => [ 'atrshmlog_error_write2_13 ' , 'Pthread specific buffer not available. ' ] ,

    -46 => [ 'atrshmlog_error_attach_7 ' , 'Pthread specific buffer not available. ' ] 

    
    );
    

foreach my $e (@ARGV) {
    &give_error_message($e);
}

exit (0);

# end of main

sub give_error_message {
    my $error = $_[0];

    $error = $error + 0;
    
    if (defined $error_map{$error}) {
	my $r = $error_map{$error};

	my $enumname = $r->[0];

	print "error $error:\n";
	print "enum is " . $enumname . "\n";

	my @t = @{$r};

	shift @t;
	
	foreach my $txt (@t) {
	    print $txt . "\n";
	}
 
    } else {
	print "no error found for $error in map.\n";
    }
}

# end of file

