#!/usr/bin/perl
#!/usr/local/bin/perl
#!/usr/pkg/bin/perl
#
# $Id:$
#
# we give a better statistics output , later we also interpret
#

if ($#ARGV < 0) {
    print "cannot work without input file.\n";
    exit(1);
}


%s = ();

%m = (
 0 => [ 'atrshmlog_counter_time_low                  ' , ' We deliver in the get function the actual click time low part ' ] ,
 1 => [ 'atrshmlog_counter_time_high                 ' , ' We deliver in the get function the actual click time high part ' ] ,
 2 => [ 'atrshmlog_counter_attach                    ' , ' The number of calls to atrshmlog_attach() ' ] ,
 3 => [ 'atrshmlog_counter_get_raw                   ' , ' The number of calls to atrshmlog_il_get_raw_buffers() ' ] ,
 4 => [ 'atrshmlog_counter_free                      ' , ' The number of calls to atrshmlog_free() ' ] ,
 5 => [ 'atrshmlog_counter_alloc                     ' , ' The number of calls to atrshmlog_alloc() ' ] ,
 6 => [ 'atrshmlog_counter_dispatch                  ' , ' The number of calls to atrshmlog_dispatch_buffer() ' ] ,
 7 => [ 'atrshmlog_counter_mem_to_shm                ' , ' The number of calls to atrshmlog_transfer_mem_to_shm() ' ] ,
 8 => [ 'atrshmlog_counter_mem_to_shm_doit           ' , ' When atrshmlog_transfer_mem_to_shm() actually starts to transfer ' ] ,
 9 => [ 'atrshmlog_counter_mem_to_shm_full           ' , ' When atrshmlog_transfer_mem_to_shm() runs into a full shm buffer system and has to wait ' ] ,
 10 => [ 'atrshmlog_counter_create_slave              ' , ' The number of calls to atrshmlog_create_slave() ' ] ,
 11 => [ 'atrshmlog_counter_stop                      ' , ' The number of calls to atrshmlog_stop() ' ] ,
 12 => [ 'atrshmlog_counter_write0                    ' , ' The number of calls to atrshmlog_write0() ' ] ,
 13 => [ 'atrshmlog_counter_write0_abort1             ' , ' When atrshmlog_write0() exits because of error ' ] ,
 14 => [ 'atrshmlog_counter_write0_abort2             ' , ' When atrshmlog_write0() exits because of error ' ] ,
 15 => [ 'atrshmlog_counter_write0_abort3             ' , ' When atrshmlog_write0() exits because of error ' ] ,
 16 => [ 'atrshmlog_counter_write0_abort4             ' , ' When atrshmlog_write0() exits because of error ' ] ,
 17 => [ 'atrshmlog_counter_write0_discard            ' , ' When atrshmlog_write0() exits because strategy discard ' ] ,
 18 => [ 'atrshmlog_counter_write0_wait               ' , ' When atrshmlog_write0() waits because strategy  ' ] ,
 19 => [ 'atrshmlog_counter_write0_adaptive           ' , ' When atrshmlog_write0() waits because strategy  ' ] ,
 20 => [ 'atrshmlog_counter_write0_adaptive_fast      ' , ' When atrshmlog_write0() waits because strategy  ' ] ,
 21 => [ 'atrshmlog_counter_write0_adaptive_very_fast ' , ' When atrshmlog_write0() waits because strategy  ' ] ,
 22 => [ 'atrshmlog_counter_write_safeguard           ' , ' When atrshmlog_write0() exits because safeguard error ' ] ,
 23 => [ 'atrshmlog_counter_write_safeguard_shm       ' , ' When atrshmlog_write0() exits because safeguard error ' ] ,
 24 => [ 'atrshmlog_counter_write1                    ' , ' The number of calls to atrshmlog_write1() ' ] ,
 25 => [ 'atrshmlog_counter_write1_abort1             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 26 => [ 'atrshmlog_counter_write1_abort2             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 27 => [ 'atrshmlog_counter_write1_abort3             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 28 => [ 'atrshmlog_counter_write1_abort4             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 29 => [ 'atrshmlog_counter_write1_discard            ' , ' When atrshmlog_write1() exits because strategy discard ' ] ,
 30 => [ 'atrshmlog_counter_write1_wait               ' , ' When atrshmlog_write1() waits because strategy ' ] ,
 31 => [ 'atrshmlog_counter_write1_adaptive           ' , ' When atrshmlog_write1() waits because strategy ' ] ,
 32 => [ 'atrshmlog_counter_write1_adaptive_fast      ' , ' When atrshmlog_write1() waits because strategy ' ] ,
 33 => [ 'atrshmlog_counter_write1_adaptive_very_fast ' , ' When atrshmlog_write1() waits because strategy ' ] ,
 34 => [ 'atrshmlog_counter_write1_abort5             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 35 => [ 'atrshmlog_counter_write1_abort6             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 36 => [ 'atrshmlog_counter_write1_abort7             ' , ' When atrshmlog_write1() exits because of error ' ] ,
 37 => [ 'atrshmlog_counter_write2                    ' , ' The number of calls to atrshmlog_write2() ' ] ,
 38 => [ 'atrshmlog_counter_write2_abort1             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 39 => [ 'atrshmlog_counter_write2_abort2             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 40 => [ 'atrshmlog_counter_write2_abort3             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 41 => [ 'atrshmlog_counter_write2_abort4             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 42 => [ 'atrshmlog_counter_write2_discard            ' , ' When atrshmlog_write2() exits because strategy discard ' ] ,
 43 => [ 'atrshmlog_counter_write2_wait               ' , ' When atrshmlog_write2() waits because strategy ' ] ,
 44 => [ 'atrshmlog_counter_write2_adaptive           ' , ' When atrshmlog_write2() waits because strategy ' ] ,
 45 => [ 'atrshmlog_counter_write2_adaptive_fast      ' , ' When atrshmlog_write2() waits because strategy ' ] ,
 46 => [ 'atrshmlog_counter_write2_adaptive_very_fast ' , ' When atrshmlog_write2() waits because strategy ' ] ,
 47 => [ 'atrshmlog_counter_write2_abort5             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 48 => [ 'atrshmlog_counter_write2_abort6             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 49 => [ 'atrshmlog_counter_write2_abort7             ' , ' When atrshmlog_write2() exits because of error ' ] ,
 50 => [ 'atrshmlog_counter_set_slave_count           ' , ' The number of calls to atrshmlog_set_f_list_buffer_slave_count() ' ] ,
 51 => [ 'atrshmlog_counter_set_clock_id              ' , ' The number of calls to atrshmlog_set_clock_id() ' ] ,
 52 => [ 'atrshmlog_counter_slave_off                 ' , ' The number of calls to atrshmlog_set_f_list_buffer_slave_run_off() ' ] ,
 53 => [ 'atrshmlog_counter_set_event_locks           ' , ' The number of calls to atrshmlog_set_event_locks_max() ' ] ,
 54 => [ 'atrshmlog_counter_set_buffer_size              ' , ' The number of calls to atrshmlog_set_buffer_infosize() ' ] ,
 55 => [ 'atrshmlog_counter_set_wait_slaves_on        ' , ' The number of calls to atrshmlog_set_wait_for_slaves_on() ' ] ,
 56 => [ 'atrshmlog_counter_set_wait_slaves_off       ' , ' The number of calls to atrshmlog_set_wait_for_slaves_off() ' ] ,
 57 => [ 'atrshmlog_counter_set_slave_wait            ' , ' The number of calls to atrshmlog_set_f_list_buffer_slave_wait() ' ] ,
 58 => [ 'atrshmlog_counter_set_prealloc_count        ' , ' The number of calls to atrshmlog_set_prealloc_buffer_count() ' ] ,
 59 => [ 'atrshmlog_counter_set_thread_fence          ' , ' The number of calls to atrshmlog_set_thread_fence() ' ] ,
 60 => [ 'atrshmlog_counter_create                    ' , ' The number of calls to atrshmlog_create() ' ] ,
 61 => [ 'atrshmlog_counter_create_abort1             ' , ' The atrshmlog_create() exits because of error ' ] ,
 62 => [ 'atrshmlog_counter_create_abort2             ' , ' The atrshmlog_create() exits because of error ' ] ,
 63 => [ 'atrshmlog_counter_create_abort3             ' , ' The atrshmlog_create() exits because of error ' ] ,
 64 => [ 'atrshmlog_counter_create_abort4             ' , ' The atrshmlog_create() exits because of error ' ] ,
 65 => [ 'atrshmlog_counter_delete                    ' , ' The number of calls to atrshmlog_delete() ' ] ,
 66 => [ 'atrshmlog_counter_cleanup_locks             ' , ' The number of calls to atrshmlog_cleanup_locks() ' ] ,
 67 => [ 'atrshmlog_counter_init_shm                  ' , ' The number of calls to atrshmlog_init_shm_log() ' ] ,
 68 => [ 'atrshmlog_counter_read                      ' , ' The number of calls to atrshmlog_read() ' ] ,
 69 => [ 'atrshmlog_counter_read_doit                 ' , ' The atrshmlog_read() transfers a buffer ' ] ,
 70 => [ 'atrshmlog_counter_read_fetch                ' , ' The number of calls to atrshmlog_read_fetch() ' ] ,
 71 => [ 'atrshmlog_counter_read_fetch_doit           ' , ' The  atrshmlog_read_fetch() transfers a buffer ' ] ,
 72 => [ 'atrshmlog_counter_verify                    ' , ' The number of calls to atrshmlog_verify() ' ] ,
 73 => [ 'atrshmlog_counter_logging_process_on        ' , ' The number of calls to atrshmlog_set_logging_process_on() ' ] ,
 74 => [ 'atrshmlog_counter_logging_process_off       ' , ' The number of calls to atrshmlog_set_logging_process_off() ' ] ,
 75 => [ 'atrshmlog_counter_set_strategy              ' , ' The number of calls to atrshmlog_set_strategy() ' ] ,
 76 => [ 'atrshmlog_counter_set_strategy_process      ' , ' The number of calls to atrshmlog_set_strategy_process() ' ] ,
 77 => [ 'atrshmlog_counter_set_event                 ' , ' The number of calls to atrshmlog_set_event_on() ' ] ,
 78 => [ 'atrshmlog_counter_set_env_prefix            ' , ' The number of calls to atrshmlog_set_event_off() ' ] ,
 79 => [ 'atrshmlog_counter_exit_cleanup              ' , ' The number of calls to atrshmlog_exit_cleanup() ' ] ,
 80 => [ 'atrshmlog_counter_flush                     ' , ' The number of calls to atrshmlog_flush() ' ] ,
 81 => [ 'atrshmlog_counter_logging_process_off_final ' , ' The number of calls to atrshmlog_set_logging_process_off_final() ' ] ,
 82 => [ 'atrshmlog_counter_turn_logging_off          ' , ' The number of calls to  atrshmlog_turn_logging_off() ' ] ,
 83 => [ 'atrshmlog_counter_init_in_advance_on        ' , ' The number of calls to  atrshmlog_init_buffers_in_advance_on() ' ] ,
 84 => [ 'atrshmlog_counter_init_in_advance_off       ' , ' The number of calls to  atrshmlog_init_buffers_in_advance_off() ' ] , 
 85 => [ 'atrshmlog_counter_reuse_thread_buffers      ' , ' The number of calls to  atrshmlog_reuse_thread_buffers() ' ] ,
 86 => [ 'atrshmlog_counter_set_autoflush             ' , ' The number of calls to  atrshmlog_set_autoflush() ']
    );

$infile = shift @ARGV;

open(IN, $infile) or die "cannot open $infile for read.\n";

while (<IN>) {

    if (m:^atrshmlogstat ([\d]+) ([\d\-]+):) {
	$s{$1} = $2 + 0;
    }
}

close IN;

# ok. here we are with a bunch of data

foreach my $k (sort { $a <=> $b } keys %s) {
    my $r = $m{$k} ;
    
    print $k . ' ' . $r->[0] . ' ' . $s{$k} . "\n";
    print '        ' . $r->[1] . "\n\n";
}

exit(0);

# end of file
