#!/bin/bash
#!/usr/local/bin/bash
#!/bin/ksh

if [ ! -d $1 ]
then
    echo "parameter one must be a filled directory tree"
    exit 1
fi

find $1 -type f -name 'atrshmlog_*.bin' | while read i
do
    atrshmlogconvert "${i}" "${i%%.bin}.txt"
done

