
# the cassandra

ATRSHMLOG_CASSKEYSPACE=atrshmlog_ks
ATRSHMLOG_CASSCONTACTPOINTS=192.168.42.7
ATRSHMLOG_CASSPORT=9042
ATRSHMLOG_CASSUSER=atrshmlog
ATRSHMLOG_CASSPWD=atrshmlog4711
export ATRSHMLOG_CASSCONTACTPOINTS
export ATRSHMLOG_CASSPORT
export ATRSHMLOG_CASSUSER
export ATRSHMLOG_CASSPWD
export ATRSHMLOG_CASSKEYSPACE


# we need libs from there

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
export LD_LIBRARY_PATH

