
# dot file for my postgres.
ATRSHMLOG_PQDBNAME=atrshmlog
ATRSHMLOG_PQHOST=hydra
ATRSHMLOG_PQHOSTADDR=192.168.42.7
ATRSHMLOG_PQPORT=5432
ATRSHMLOG_PQDBNAME=atrshmlog
ATRSHMLOG_PQUSER=atrshmlog
ATRSHMLOG_PQPWD=atrshmlog4711
export ATRSHMLOG_PQHOST
export ATRSHMLOG_PQHOSTADDR
export ATRSHMLOG_PQPORT
export ATRSHMLOG_PQUSER
export ATRSHMLOG_PQPWD
export ATRSHMLOG_PQDBNAME

