#!/bin/bash

if [ ! -d $1 ]
then
    echo "parameter one must be a filled directory"
    exit 1
fi

find $1 -type d -name '[0-9]*' | while read i
do
    #    cat $i/b*.txt |sort -s -n -k 3 -k 4 > $i/prot.txt
        cat $i/atrshmlog_*.txt |sort -s -n -k 5  > $i/prot.txt
done

